### ISSUE TITLE
No lecture on 2020-02-04

### ISSUE THREAD

**Issue by tomtomjhj** [kaist-cp/study-csl#10]

**Comment by leeopop** [comment]
Do you suggest any additional HW/material to make our next session more valuable?
It would be great to have a challenging statement to prove, if it is possible to prove using our previous seminar materials.

**Comment by tomtomjhj** [comment]
I'd recommend some examples from the iris lecture note
* 7.8 `spawn`, `join` and `par`. https://gitlab.mpi-sws.org/iris/iris/blob/master/theories/heap_lang/lib/spawn.v, https://gitlab.mpi-sws.org/iris/iris/blob/master/theories/heap_lang/lib/par.v
* 8 concurrent stacks https://gitlab.mpi-sws.org/iris/examples/tree/master/theories/concurrent_stacks
* 9 ticket lock https://gitlab.mpi-sws.org/iris/iris/blob/master/theories/heap_lang/lib/ticket_lock.v
